### ISSUE TITLE
Can it extend to a batch version?

### ISSUE THREAD

**Issue by daidaren202** [CUVL/Differentiable-Frechet-Mean#1]
Hi, thanks for your great work that provides a solution to calculate the Frechet mean.

The code you released only supports to calculate one 'mean' for a set of points on some manifold. Do you plan to realize a version for batch compution. 

By the way, it seems to be time-consuming while  the hyper-parameter "max_iter" is set to 1000 defaultly. Is there any suggestion or experiment evaluation of trade-off between the time complexity and accuracy? 

Best regards.

**Comment by louaaron** [comment]
Hi!

Our code should work for batched mean computation (I think we explicitly enumerate this in the files as [..., dim]). The max_iter hyper-parameter is mainly used as a failsafe to avoid infinite loops. The actual computation shouldn't take 1000 iterations to converge, so there may be a more fundamental issue with your test case; for our application instances, we saw convergence in ~16-50 iterations.

**Comment by daidaren202** [comment]
Oh! I noticed it.  Thanks for your patient answer!
